name: Profile summary cards

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzj5/github-profile-summary-cards@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ShahabAhmed01
          BRANCH_NAME: profile-summary-card
          THEME: github_dark
